import random

BAG_SIZE = 8
MAX_ITENS = 3
TOTAL_ITENS_SIZE = 5
TOTAL_ITENS_BENEFIT = 6
POPULATION_SIZE = 5


SELECTION_PERCENT = 90
MUTATION_PERCENT = 25
MAX_ITERATION = 10000

# ITENS = [[random.randint(1, MAX_ITENS), random.randint(1, TOTAL_ITENS_BENEFIT)] for i in range(MAX_ITENS)]
ITENS = [[3, 2], [5, 6], [2, 3]]
