import random

BAG_SIZE = 1000
MAX_ITENS = 200
TOTAL_ITENS_SIZE = 20
TOTAL_ITENS_BENEFIT = 70

ITENS = [[random.randint(1, TOTAL_ITENS_SIZE), random.randint(1, TOTAL_ITENS_BENEFIT)] for i in range(MAX_ITENS)]

# Algorithm settings
POPULATION_SIZE = 40
SELECTION_PERCENT = 90
MUTATION_PERCENT = 10
MAX_ITERATION = 100
